### ISSUE TITLE
setAmount not working

### ISSUE THREAD

**Issue by rahul260792** [geeckmc/CardForm#2]
I am using the following code to change the Amount displayed on the form but it always remain as $500.
```
CardForm cardForm = (CardForm)findViewById(R.id.card_form);
        cardForm.setAmount("$6000");
        cardForm.setPayBtnClickListner(new OnPayBtnClickListner() {
            @Override
            public void onClick(Card card) {
                Toast.makeText(getApplicationContext(),card.getNumber(),Toast.LENGTH_SHORT).show();
            }
        });
```

**Comment by saintjab** [comment]
You probably want to create the setters your self. I faced similar problem so I created setters for all the fields I need so now am able to load the data from SharedPreference and load it into the fields.
